### ISSUE TITLE
JMAP.mail.setFlagged is not a function

### ISSUE THREAD

**Issue by s77rt** [jmapio/jmap-demo-webmail#11]
Hi,
Thanks for your work :)

Seems that the demo is trying to call a function that does not even exist in the library ?
`JMAP.mail.setFlagged is not a function TypeError: JMAP.mail.setFlagged is not a function`
happens when trying to star/flag an email

**Comment by neilj** [comment]
Fixed; the library API changed and the demo needed to be updated.
