### ISSUE TITLE
SyntaxError Failed to construct 'EventSource': Cannot open an EventSource to an empty URL.

### ISSUE THREAD

**Issue by s77rt** [jmapio/jmap-demo-webmail#12]
This error happens just after the upgrade to the current commit...
`SyntaxError Failed to construct 'EventSource': Cannot open an EventSource to an empty URL.`

Also the login button does not seem to work:
`TypeError target[action] is not a function TypeError: target[action] is not a function`

**Comment by s77rt** [comment]
the second error, is just a consequence of the first error.
i temporarily set eventSourceUrl in JMAP.js to '#' instead of '', it worked (with an error: `EventSource's response has a MIME type ("text/html") that is not "text/event-stream". Aborting the connection.`)

i'm not sure if the change should be done in the library itself or the app.

hope you can fix this asap :)

**Comment by neilj** [comment]
Fixed.
