### ISSUE TITLE
Can't move an email

### ISSUE THREAD

**Issue by s77rt** [jmapio/jmap-demo-webmail#13]
Hi,
I can't move any email, and getting the following error message:
`ReferenceError FASTMAIL is not defined ReferenceError: FASTMAIL is not defined`

**Comment by neilj** [comment]
Fixed.

**Comment by s77rt** [comment]
@neilj 
thanks for the fix, however you can't move an email from the trash to anywhere, which is a little confusing to the user, hope you can make a fix for that
