### ISSUE TITLE
JMAP.js: parseStructure() differs from spec

### ISSUE THREAD

**Issue by stokito** [jmapio/jmap-demo-webmail#19]
In [the spec](https://jmap.io/spec-mail.html#body-parts) is shown an example of parseStructure().
I see the same function in the JMAP.js but it very differs. Could you please say which one version is better and newer?

**Comment by neilj** [comment]
There's no one "right" answer here, hence the spec only giving the code as a starting point, however the version in JMAP.js is the one we currently use at Fastmail in our UI.
