### ISSUE TITLE
Connect to MS Exchange server?

### ISSUE THREAD

**Issue by jkleiser** [jmapio/jmap-demo-webmail#2]
Can JMAP be used to connect to a MS Exchange server?
If yes, could you please give me a hint on how to setup the JMAP.auth.didAuthenticate?

**Comment by neilj** [comment]
[JMAP](http://jmap.io) is a protocol. Exchange does not talk JMAP natively (at least at the moment). The [JMAP Proxy](https://github.com/jmapio/jmap-perl) provides a JMAP interface to IMAP servers. Some configurations of Exchange support IMAP, so it may be possible to use this.

This project is a demo webmail, which is a JavaScript app that talks to a JMAP server and provides a user interface.
