### ISSUE TITLE
Yandex Email doesn't work?

### ISSUE THREAD

**Issue by JAB-Freeware** [jmapio/jmap-demo-webmail#4]
When I try via IMAP I get this error "No known authentication method supported"

Is this a limitation of JMAP or the demo? If imap/smtp is enabled/supported on the email server JMAP should work right?

**Comment by neilj** [comment]
This repo is just for the frontend UI demo. This sounds like a potential issue with the Perl proxy that connects to and IMAP store; you can find that repo at https://github.com/jmapio/jmap-perl and file an issue.

Please not, JMAP itself is a specification for an application synchronisation protocol, independent of IMAP, so I'm not sure what you mean by "limitation of JMAP" in this context.
