### ISSUE TITLE
AOL & Google OAuth

### ISSUE THREAD

**Issue by BigNateBombBomb** [jmapio/jmap-demo-webmail#9]
Looks like you guys never went through the recent Google mail security review for your demo client and the AOL one just comes up with some unknown error page. I can definitely see how you wouldn't want to bother through all that hassle of the Google review for a demo page, so maybe just take down the OAuth part of the demo, or a short blurb about having to fork the repo and provide your own credentials?

**Comment by brong** [comment]
Yep, sadly the Google mail security review denied us because it's a "demo project" and they don't allow that.  I'll have a look at this soon.
